plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'maven-publish'
}

group 'homer.database'
version 'beta-1.2.0'

repositories {
    mavenCentral()
}

sourceCompatibility = '9'
targetCompatibility = '9'

dependencies {
    implementation 'com.google.guava:guava:33.3.1-jre'
}

shadowJar {
    archiveBaseName.set('HomerDataBase')
    archiveClassifier.set('backend')
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'backend'
        }
    }
    repositories {
        maven {
            url = uri("${rootDir}/../local-repo")
        }
    }
}