plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'maven-publish'
}

group 'homer.database'
version 'beta-1.2.0'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
    maven {
        url uri("${rootDir}/../local-repo")
    }
}

sourceCompatibility = '9'
targetCompatibility = '9'

dependencies {
    // implementation name: 'HomerDataBase-1.0.0-backend'
    implementation 'homer.database:backend:beta-1.2.0'
}

shadowJar {
    archiveBaseName.set('HomerDataBase')
    archiveClassifier.set('converter')
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }
    dependencies {
        exclude(dependency(':HomerDataBase-1.0.0-backend'))
        exclude(dependency('homer.database:backend:beta-1.2.0'))
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'converter'
        }
    }
    repositories {
        maven {
            url = uri("${rootDir}/../local-repo")
        }
    }
}