plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'homer.convertor'
version '1.0'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

sourceCompatibility = '9'
targetCompatibility = '9'

dependencies {
    implementation name: 'HomerDataBase-backend-1.1.3-WithDependencies'
}

jar {
    archivesBaseName = 'HomerDataBase-convertor'
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }
}

shadowJar {
    archiveBaseName.set('HomerDataBase-convertor')
    archiveClassifier.set('WithDependencies')
    manifest {
        attributes(
                'Implementation-Title': project.name,
                'Implementation-Version': project.version
        )
    }
    dependencies {
        exclude(dependency(':HomerDataBase-backend-1.1.3-WithDependencies'))
    }
}